name: dev_analytics_dashboard_example
description: "Demonstrates how to use the dev_analytics_dashboard plugin."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dev_analytics_dashboard:

    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

