name: dev_analytics_dashboard
description: "Flutter Dev Analytics Dashboard for version 0.0.1 with features: device info, performance metrics, screen logs, error tracking, user flow visualization, and a gesture-based toggle."
version: 0.0.1
homepage: https://github.com/santhosh-ceo/dev_analytics_dashboard

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.0
  statsfl: ^2.3.0
  system_info2: ^4.0.0
  provider: ^6.1.2
  flutter_logs: ^2.1.2
  fl_chart: ^0.68.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.example.dev_analytics_dashboard
        pluginClass: DevAnalyticsDashboardPlugin
      ios:
        pluginClass: DevAnalyticsDashboardPlugin